/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pontodelivery;

/**
 *
 * @author Administrator
 */
public class RelatórioFinanceiroView extends javax.swing.JFrame {

    /**
     * Creates new form RelatórioFinanceiroView
     */
    public RelatórioFinanceiroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblSubtituloCadastro = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        btnSalvarProduto = new javax.swing.JButton();
        lblTituloLogin1 = new javax.swing.JLabel();
        jLabelSeg = new javax.swing.JLabel();
        jLabelTer = new javax.swing.JLabel();
        jLabelSex = new javax.swing.JLabel();
        jLabelSab = new javax.swing.JLabel();
        jLabelDom = new javax.swing.JLabel();
        progressSeg = new javax.swing.JProgressBar();
        progressTer = new javax.swing.JProgressBar();
        progressQua = new javax.swing.JProgressBar();
        jLabelTer1 = new javax.swing.JLabel();
        jLabelSex1 = new javax.swing.JLabel();
        progressQui = new javax.swing.JProgressBar();
        progressSex = new javax.swing.JProgressBar();
        progressSab = new javax.swing.JProgressBar();
        progressDom = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSubtituloCadastro.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblSubtituloCadastro.setText("RELATÓRIO FINANCEIRO  ");

        lblNomeProduto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblNomeProduto.setText("Relatório - JUN/2024");

        btnSalvarProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvarProduto.setText("EXPORTAR");
        btnSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutoActionPerformed(evt);
            }
        });

        lblTituloLogin1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblTituloLogin1.setText("SR. MANOEL PIZZARIA");

        jLabelSeg.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelSeg.setText("SEG");

        jLabelTer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelTer.setText("TER");

        jLabelSex.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelSex.setText("SEX");

        jLabelSab.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelSab.setText("SAB");

        jLabelDom.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelDom.setText("DOM");

        progressSeg.setValue(60);

        progressTer.setValue(60);

        progressQua.setValue(40);

        jLabelTer1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelTer1.setText("QUA");

        jLabelSex1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelSex1.setText("QUI");

        progressQui.setValue(30);

        progressSex.setValue(10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(lblTituloLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtituloCadastro)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelSeg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(progressSeg, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelTer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(progressTer, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelSex1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(progressQui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelTer1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(progressQua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSex)
                            .addComponent(jLabelSab)
                            .addComponent(jLabelDom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressSex, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressDom, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressSab, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblNomeProduto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnSalvarProduto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeProduto)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSeg)
                    .addComponent(progressSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressTer, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTer))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTer1)
                    .addComponent(progressQua, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSex1)
                    .addComponent(progressQui, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressSex, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSab)
                    .addComponent(progressSab, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDom)
                    .addComponent(progressDom, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvarProduto)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutoActionPerformed
        try {
            // Define os valores dos progress bars
            progressSeg.setValue(60);
            progressTer.setValue(60);
            progressQua.setValue(40);
            progressQui.setValue(30);
            progressSex.setValue(10);
            progressSab.setValue(20);  // valor definido para sábado
            progressDom.setValue(50);  // valor definido para domingo

            // Cria e escreve no arquivo relatorio_financeiro.txt
            java.io.FileWriter fw = new java.io.FileWriter("relatorio_financeiro.txt");
            fw.write("Relatório Financeiro - JUN/2024\n");
            fw.write("SEG: " + progressSeg.getValue() + "%\n");
            fw.write("TER: " + progressTer.getValue() + "%\n");
            fw.write("QUA: " + progressQua.getValue() + "%\n");
            fw.write("QUI: " + progressQui.getValue() + "%\n");
            fw.write("SEX: " + progressSex.getValue() + "%\n");
            fw.write("SAB: " + progressSab.getValue() + "%\n");
            fw.write("DOM: " + progressDom.getValue() + "%\n");
            fw.close();

            javax.swing.JOptionPane.showMessageDialog(this, "Relatório exportado com sucesso!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao exportar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatórioFinanceiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatórioFinanceiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatórioFinanceiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatórioFinanceiroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatórioFinanceiroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarProduto;
    private javax.swing.JLabel jLabelDom;
    private javax.swing.JLabel jLabelSab;
    private javax.swing.JLabel jLabelSeg;
    private javax.swing.JLabel jLabelSex;
    private javax.swing.JLabel jLabelSex1;
    private javax.swing.JLabel jLabelTer;
    private javax.swing.JLabel jLabelTer1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblSubtituloCadastro;
    private javax.swing.JLabel lblTituloLogin1;
    private javax.swing.JProgressBar progressDom;
    private javax.swing.JProgressBar progressQua;
    private javax.swing.JProgressBar progressQui;
    private javax.swing.JProgressBar progressSab;
    private javax.swing.JProgressBar progressSeg;
    private javax.swing.JProgressBar progressSex;
    private javax.swing.JProgressBar progressTer;
    // End of variables declaration//GEN-END:variables
}
